//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_OUT
    {
        public long ID_CHECKOUT { get; set; }
        public Nullable<long> ID_MULTA { get; set; }
        public long ID_DEPTO { get; set; }
        public long ID_RESERVA { get; set; }
        public byte[] DOCUMENTO_ENTREGA { get; set; }
    
        public virtual DEPTOS DEPTOS { get; set; }
        public virtual MULTAS MULTAS { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
