//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTAS
    {
        public MULTAS()
        {
            this.CHECK_OUT = new HashSet<CHECK_OUT>();
        }
    
        public long ID_MULTA { get; set; }
        public string DETALLE { get; set; }
        public long VALOR_MULTA { get; set; }
    
        public virtual ICollection<CHECK_OUT> CHECK_OUT { get; set; }
    }
}
