//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO_RESERVA
    {
        public PAGO_RESERVA()
        {
            this.CHECK_IN = new HashSet<CHECK_IN>();
        }
    
        public long ID_PAGO { get; set; }
        public long ID_RESERVA { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
        public long MONTO { get; set; }
    
        public virtual ICollection<CHECK_IN> CHECK_IN { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
