//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.CHECK_OUT = new HashSet<CHECK_OUT>();
            this.PAGO_RESERVA = new HashSet<PAGO_RESERVA>();
            this.SERVICIOS_EXTRA = new HashSet<SERVICIOS_EXTRA>();
        }
    
        public long ID_RESERVA { get; set; }
        public long ID_USER { get; set; }
        public long ID_DEPTO { get; set; }
        public System.DateTime FECHA_RESERVA { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
    
        public virtual ICollection<CHECK_OUT> CHECK_OUT { get; set; }
        public virtual DEPTOS DEPTOS { get; set; }
        public virtual ICollection<PAGO_RESERVA> PAGO_RESERVA { get; set; }
        public virtual ICollection<SERVICIOS_EXTRA> SERVICIOS_EXTRA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
