//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TurismoRealEntities : DbContext
    {
        public TurismoRealEntities()
            : base("name=TurismoRealEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHECK_IN> CHECK_IN { get; set; }
        public DbSet<CHECK_OUT> CHECK_OUT { get; set; }
        public DbSet<DEPTOS> DEPTOS { get; set; }
        public DbSet<FOTO_DEPTO> FOTO_DEPTO { get; set; }
        public DbSet<ITEMS_DEPTO> ITEMS_DEPTO { get; set; }
        public DbSet<MULTAS> MULTAS { get; set; }
        public DbSet<PAGO_RESERVA> PAGO_RESERVA { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<SERVICIOS_EXTRA> SERVICIOS_EXTRA { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
    
        public virtual int SP_CREATE_CHECKIN(Nullable<decimal> v_IDCHECKIN, Nullable<decimal> v_IDDEPTO, Nullable<decimal> v_IDPAGO, Nullable<decimal> v_IDSERVICIO, byte[] v_DOCUMENTO)
        {
            var v_IDCHECKINParameter = v_IDCHECKIN.HasValue ?
                new ObjectParameter("V_IDCHECKIN", v_IDCHECKIN) :
                new ObjectParameter("V_IDCHECKIN", typeof(decimal));
    
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_IDPAGOParameter = v_IDPAGO.HasValue ?
                new ObjectParameter("V_IDPAGO", v_IDPAGO) :
                new ObjectParameter("V_IDPAGO", typeof(decimal));
    
            var v_IDSERVICIOParameter = v_IDSERVICIO.HasValue ?
                new ObjectParameter("V_IDSERVICIO", v_IDSERVICIO) :
                new ObjectParameter("V_IDSERVICIO", typeof(decimal));
    
            var v_DOCUMENTOParameter = v_DOCUMENTO != null ?
                new ObjectParameter("V_DOCUMENTO", v_DOCUMENTO) :
                new ObjectParameter("V_DOCUMENTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CHECKIN", v_IDCHECKINParameter, v_IDDEPTOParameter, v_IDPAGOParameter, v_IDSERVICIOParameter, v_DOCUMENTOParameter);
        }
    
        public virtual int SP_CREATE_CHECKOUT(Nullable<decimal> v_IDCHECKOUT, Nullable<decimal> v_IDMULTA, Nullable<decimal> v_IDDEPTO, Nullable<decimal> v_IDRESERVA, byte[] v_DOCUMENTO)
        {
            var v_IDCHECKOUTParameter = v_IDCHECKOUT.HasValue ?
                new ObjectParameter("V_IDCHECKOUT", v_IDCHECKOUT) :
                new ObjectParameter("V_IDCHECKOUT", typeof(decimal));
    
            var v_IDMULTAParameter = v_IDMULTA.HasValue ?
                new ObjectParameter("V_IDMULTA", v_IDMULTA) :
                new ObjectParameter("V_IDMULTA", typeof(decimal));
    
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_IDRESERVAParameter = v_IDRESERVA.HasValue ?
                new ObjectParameter("V_IDRESERVA", v_IDRESERVA) :
                new ObjectParameter("V_IDRESERVA", typeof(decimal));
    
            var v_DOCUMENTOParameter = v_DOCUMENTO != null ?
                new ObjectParameter("V_DOCUMENTO", v_DOCUMENTO) :
                new ObjectParameter("V_DOCUMENTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CHECKOUT", v_IDCHECKOUTParameter, v_IDMULTAParameter, v_IDDEPTOParameter, v_IDRESERVAParameter, v_DOCUMENTOParameter);
        }
    
        public virtual int SP_CREATE_DEPTOS(Nullable<decimal> v_IDDEPTO, Nullable<decimal> v_DISP, string v_ESTADO, string v_REGION, string v_COMUNA, string v_DIRECCION, Nullable<decimal> v_PRECIODIA)
        {
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_DISPParameter = v_DISP.HasValue ?
                new ObjectParameter("V_DISP", v_DISP) :
                new ObjectParameter("V_DISP", typeof(decimal));
    
            var v_ESTADOParameter = v_ESTADO != null ?
                new ObjectParameter("V_ESTADO", v_ESTADO) :
                new ObjectParameter("V_ESTADO", typeof(string));
    
            var v_REGIONParameter = v_REGION != null ?
                new ObjectParameter("V_REGION", v_REGION) :
                new ObjectParameter("V_REGION", typeof(string));
    
            var v_COMUNAParameter = v_COMUNA != null ?
                new ObjectParameter("V_COMUNA", v_COMUNA) :
                new ObjectParameter("V_COMUNA", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_PRECIODIAParameter = v_PRECIODIA.HasValue ?
                new ObjectParameter("V_PRECIODIA", v_PRECIODIA) :
                new ObjectParameter("V_PRECIODIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_DEPTOS", v_IDDEPTOParameter, v_DISPParameter, v_ESTADOParameter, v_REGIONParameter, v_COMUNAParameter, v_DIRECCIONParameter, v_PRECIODIAParameter);
        }
    
        public virtual int SP_CREATE_FOTODEPTO(Nullable<decimal> v_IDDEPTO, byte[] v_FOTO)
        {
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_FOTOParameter = v_FOTO != null ?
                new ObjectParameter("V_FOTO", v_FOTO) :
                new ObjectParameter("V_FOTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_FOTODEPTO", v_IDDEPTOParameter, v_FOTOParameter);
        }
    
        public virtual int SP_CREATE_ITEMSDEPTO(Nullable<decimal> v_IDITEM, Nullable<decimal> v_IDDEPTO, string v_DESCRIPCION, Nullable<decimal> v_VALOR)
        {
            var v_IDITEMParameter = v_IDITEM.HasValue ?
                new ObjectParameter("V_IDITEM", v_IDITEM) :
                new ObjectParameter("V_IDITEM", typeof(decimal));
    
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            var v_VALORParameter = v_VALOR.HasValue ?
                new ObjectParameter("V_VALOR", v_VALOR) :
                new ObjectParameter("V_VALOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_ITEMSDEPTO", v_IDITEMParameter, v_IDDEPTOParameter, v_DESCRIPCIONParameter, v_VALORParameter);
        }
    
        public virtual int SP_CREATE_MULTAS(Nullable<decimal> v_IDMULTA, string v_DETALLE, Nullable<decimal> v_VALORMULTA)
        {
            var v_IDMULTAParameter = v_IDMULTA.HasValue ?
                new ObjectParameter("V_IDMULTA", v_IDMULTA) :
                new ObjectParameter("V_IDMULTA", typeof(decimal));
    
            var v_DETALLEParameter = v_DETALLE != null ?
                new ObjectParameter("V_DETALLE", v_DETALLE) :
                new ObjectParameter("V_DETALLE", typeof(string));
    
            var v_VALORMULTAParameter = v_VALORMULTA.HasValue ?
                new ObjectParameter("V_VALORMULTA", v_VALORMULTA) :
                new ObjectParameter("V_VALORMULTA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_MULTAS", v_IDMULTAParameter, v_DETALLEParameter, v_VALORMULTAParameter);
        }
    
        public virtual int SP_CREATE_PAGORESERVA(Nullable<decimal> v_IDPAGO, Nullable<decimal> v_IDRESERVA, Nullable<System.DateTime> v_FECHAPAGO, Nullable<decimal> v_MONTO)
        {
            var v_IDPAGOParameter = v_IDPAGO.HasValue ?
                new ObjectParameter("V_IDPAGO", v_IDPAGO) :
                new ObjectParameter("V_IDPAGO", typeof(decimal));
    
            var v_IDRESERVAParameter = v_IDRESERVA.HasValue ?
                new ObjectParameter("V_IDRESERVA", v_IDRESERVA) :
                new ObjectParameter("V_IDRESERVA", typeof(decimal));
    
            var v_FECHAPAGOParameter = v_FECHAPAGO.HasValue ?
                new ObjectParameter("V_FECHAPAGO", v_FECHAPAGO) :
                new ObjectParameter("V_FECHAPAGO", typeof(System.DateTime));
    
            var v_MONTOParameter = v_MONTO.HasValue ?
                new ObjectParameter("V_MONTO", v_MONTO) :
                new ObjectParameter("V_MONTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PAGORESERVA", v_IDPAGOParameter, v_IDRESERVAParameter, v_FECHAPAGOParameter, v_MONTOParameter);
        }
    
        public virtual int SP_CREATE_RESERVA(Nullable<decimal> v_IDRESERVA, Nullable<decimal> v_IDUSER, Nullable<decimal> v_IDDEPTO, Nullable<System.DateTime> v_FECHARESERVA, Nullable<System.DateTime> v_FECHAINICIO, Nullable<System.DateTime> v_FECHATERMINO)
        {
            var v_IDRESERVAParameter = v_IDRESERVA.HasValue ?
                new ObjectParameter("V_IDRESERVA", v_IDRESERVA) :
                new ObjectParameter("V_IDRESERVA", typeof(decimal));
    
            var v_IDUSERParameter = v_IDUSER.HasValue ?
                new ObjectParameter("V_IDUSER", v_IDUSER) :
                new ObjectParameter("V_IDUSER", typeof(decimal));
    
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_FECHARESERVAParameter = v_FECHARESERVA.HasValue ?
                new ObjectParameter("V_FECHARESERVA", v_FECHARESERVA) :
                new ObjectParameter("V_FECHARESERVA", typeof(System.DateTime));
    
            var v_FECHAINICIOParameter = v_FECHAINICIO.HasValue ?
                new ObjectParameter("V_FECHAINICIO", v_FECHAINICIO) :
                new ObjectParameter("V_FECHAINICIO", typeof(System.DateTime));
    
            var v_FECHATERMINOParameter = v_FECHATERMINO.HasValue ?
                new ObjectParameter("V_FECHATERMINO", v_FECHATERMINO) :
                new ObjectParameter("V_FECHATERMINO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_RESERVA", v_IDRESERVAParameter, v_IDUSERParameter, v_IDDEPTOParameter, v_FECHARESERVAParameter, v_FECHAINICIOParameter, v_FECHATERMINOParameter);
        }
    
        public virtual int SP_CREATE_SERVICIOSEXTRA(Nullable<decimal> v_IDSERVICIO, Nullable<decimal> v_IDRESERVA, string v_NOMBRESERVICIO, string v_DESCRIPCION)
        {
            var v_IDSERVICIOParameter = v_IDSERVICIO.HasValue ?
                new ObjectParameter("V_IDSERVICIO", v_IDSERVICIO) :
                new ObjectParameter("V_IDSERVICIO", typeof(decimal));
    
            var v_IDRESERVAParameter = v_IDRESERVA.HasValue ?
                new ObjectParameter("V_IDRESERVA", v_IDRESERVA) :
                new ObjectParameter("V_IDRESERVA", typeof(decimal));
    
            var v_NOMBRESERVICIOParameter = v_NOMBRESERVICIO != null ?
                new ObjectParameter("V_NOMBRESERVICIO", v_NOMBRESERVICIO) :
                new ObjectParameter("V_NOMBRESERVICIO", typeof(string));
    
            var v_DESCRIPCIONParameter = v_DESCRIPCION != null ?
                new ObjectParameter("V_DESCRIPCION", v_DESCRIPCION) :
                new ObjectParameter("V_DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_SERVICIOSEXTRA", v_IDSERVICIOParameter, v_IDRESERVAParameter, v_NOMBRESERVICIOParameter, v_DESCRIPCIONParameter);
        }
    
        public virtual int SP_CREATE_TIPOUSUARIO(Nullable<decimal> v_IDUSER, string v_TIPOCTA)
        {
            var v_IDUSERParameter = v_IDUSER.HasValue ?
                new ObjectParameter("V_IDUSER", v_IDUSER) :
                new ObjectParameter("V_IDUSER", typeof(decimal));
    
            var v_TIPOCTAParameter = v_TIPOCTA != null ?
                new ObjectParameter("V_TIPOCTA", v_TIPOCTA) :
                new ObjectParameter("V_TIPOCTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_TIPOUSUARIO", v_IDUSERParameter, v_TIPOCTAParameter);
        }
    
        public virtual int SP_CREATE_USUARIOS(Nullable<decimal> v_IDUSER, string v_EMAIL, string v_TIPOCTA, string v_PNOM, string v_SNOM, string v_PAPE, string v_SAPE, Nullable<decimal> v_RUT, string v_DVER, string v_CARGO)
        {
            var v_IDUSERParameter = v_IDUSER.HasValue ?
                new ObjectParameter("V_IDUSER", v_IDUSER) :
                new ObjectParameter("V_IDUSER", typeof(decimal));
    
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            var v_TIPOCTAParameter = v_TIPOCTA != null ?
                new ObjectParameter("V_TIPOCTA", v_TIPOCTA) :
                new ObjectParameter("V_TIPOCTA", typeof(string));
    
            var v_PNOMParameter = v_PNOM != null ?
                new ObjectParameter("V_PNOM", v_PNOM) :
                new ObjectParameter("V_PNOM", typeof(string));
    
            var v_SNOMParameter = v_SNOM != null ?
                new ObjectParameter("V_SNOM", v_SNOM) :
                new ObjectParameter("V_SNOM", typeof(string));
    
            var v_PAPEParameter = v_PAPE != null ?
                new ObjectParameter("V_PAPE", v_PAPE) :
                new ObjectParameter("V_PAPE", typeof(string));
    
            var v_SAPEParameter = v_SAPE != null ?
                new ObjectParameter("V_SAPE", v_SAPE) :
                new ObjectParameter("V_SAPE", typeof(string));
    
            var v_RUTParameter = v_RUT.HasValue ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(decimal));
    
            var v_DVERParameter = v_DVER != null ?
                new ObjectParameter("V_DVER", v_DVER) :
                new ObjectParameter("V_DVER", typeof(string));
    
            var v_CARGOParameter = v_CARGO != null ?
                new ObjectParameter("V_CARGO", v_CARGO) :
                new ObjectParameter("V_CARGO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_USUARIOS", v_IDUSERParameter, v_EMAILParameter, v_TIPOCTAParameter, v_PNOMParameter, v_SNOMParameter, v_PAPEParameter, v_SAPEParameter, v_RUTParameter, v_DVERParameter, v_CARGOParameter);
        }
    
        public virtual int SP_DELETE_CHECKIN(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CHECKIN", v_IDParameter);
        }
    
        public virtual int SP_DELETE_CHECKOUT(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CHECKOUT", v_IDParameter);
        }
    
        public virtual int SP_DELETE_DEPTOS(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_DEPTOS", v_IDParameter);
        }
    
        public virtual int SP_DELETE_FOTODEPTO(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_FOTODEPTO", v_IDParameter);
        }
    
        public virtual int SP_DELETE_ITEMSDEPTO(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_ITEMSDEPTO", v_IDParameter);
        }
    
        public virtual int SP_DELETE_MULTAS(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_MULTAS", v_IDParameter);
        }
    
        public virtual int SP_DELETE_PAGORESERVA(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_PAGORESERVA", v_IDParameter);
        }
    
        public virtual int SP_DELETE_RESERVA(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_RESERVA", v_IDParameter);
        }
    
        public virtual int SP_DELETE_SERVICIOSEXTRA(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_SERVICIOSEXTRA", v_IDParameter);
        }
    
        public virtual int SP_DELETE_TIPOUSUARIO(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_TIPOUSUARIO", v_IDParameter);
        }
    
        public virtual int SP_DELETE_USUARIO(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_USUARIO", v_IDParameter);
        }
    
        public virtual int SP_UPDATE_CHECKIN(Nullable<decimal> v_IDCHECKIN, Nullable<decimal> v_IDDEPTO, Nullable<decimal> v_IDPAGO, Nullable<decimal> v_IDSERVICIO, byte[] v_DOCUMENTO)
        {
            var v_IDCHECKINParameter = v_IDCHECKIN.HasValue ?
                new ObjectParameter("V_IDCHECKIN", v_IDCHECKIN) :
                new ObjectParameter("V_IDCHECKIN", typeof(decimal));
    
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_IDPAGOParameter = v_IDPAGO.HasValue ?
                new ObjectParameter("V_IDPAGO", v_IDPAGO) :
                new ObjectParameter("V_IDPAGO", typeof(decimal));
    
            var v_IDSERVICIOParameter = v_IDSERVICIO.HasValue ?
                new ObjectParameter("V_IDSERVICIO", v_IDSERVICIO) :
                new ObjectParameter("V_IDSERVICIO", typeof(decimal));
    
            var v_DOCUMENTOParameter = v_DOCUMENTO != null ?
                new ObjectParameter("V_DOCUMENTO", v_DOCUMENTO) :
                new ObjectParameter("V_DOCUMENTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CHECKIN", v_IDCHECKINParameter, v_IDDEPTOParameter, v_IDPAGOParameter, v_IDSERVICIOParameter, v_DOCUMENTOParameter);
        }
    
        public virtual int SP_UPDATE_CHECKOUT(Nullable<decimal> v_IDCHECKOUT, Nullable<decimal> v_IDMULTA, Nullable<decimal> v_IDDEPTO, Nullable<decimal> v_IDRESERVA, byte[] v_DOCUMENTO)
        {
            var v_IDCHECKOUTParameter = v_IDCHECKOUT.HasValue ?
                new ObjectParameter("V_IDCHECKOUT", v_IDCHECKOUT) :
                new ObjectParameter("V_IDCHECKOUT", typeof(decimal));
    
            var v_IDMULTAParameter = v_IDMULTA.HasValue ?
                new ObjectParameter("V_IDMULTA", v_IDMULTA) :
                new ObjectParameter("V_IDMULTA", typeof(decimal));
    
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_IDRESERVAParameter = v_IDRESERVA.HasValue ?
                new ObjectParameter("V_IDRESERVA", v_IDRESERVA) :
                new ObjectParameter("V_IDRESERVA", typeof(decimal));
    
            var v_DOCUMENTOParameter = v_DOCUMENTO != null ?
                new ObjectParameter("V_DOCUMENTO", v_DOCUMENTO) :
                new ObjectParameter("V_DOCUMENTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CHECKOUT", v_IDCHECKOUTParameter, v_IDMULTAParameter, v_IDDEPTOParameter, v_IDRESERVAParameter, v_DOCUMENTOParameter);
        }
    
        public virtual int SP_UPDATE_DEPTOS(Nullable<decimal> v_IDDEPTO, Nullable<decimal> v_DISPONIBILIDAD, string v_ESTADO, string v_REGION, string v_COMUNA, string v_DIRECCION, Nullable<decimal> v_PRECIODIA)
        {
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_DISPONIBILIDADParameter = v_DISPONIBILIDAD.HasValue ?
                new ObjectParameter("V_DISPONIBILIDAD", v_DISPONIBILIDAD) :
                new ObjectParameter("V_DISPONIBILIDAD", typeof(decimal));
    
            var v_ESTADOParameter = v_ESTADO != null ?
                new ObjectParameter("V_ESTADO", v_ESTADO) :
                new ObjectParameter("V_ESTADO", typeof(string));
    
            var v_REGIONParameter = v_REGION != null ?
                new ObjectParameter("V_REGION", v_REGION) :
                new ObjectParameter("V_REGION", typeof(string));
    
            var v_COMUNAParameter = v_COMUNA != null ?
                new ObjectParameter("V_COMUNA", v_COMUNA) :
                new ObjectParameter("V_COMUNA", typeof(string));
    
            var v_DIRECCIONParameter = v_DIRECCION != null ?
                new ObjectParameter("V_DIRECCION", v_DIRECCION) :
                new ObjectParameter("V_DIRECCION", typeof(string));
    
            var v_PRECIODIAParameter = v_PRECIODIA.HasValue ?
                new ObjectParameter("V_PRECIODIA", v_PRECIODIA) :
                new ObjectParameter("V_PRECIODIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_DEPTOS", v_IDDEPTOParameter, v_DISPONIBILIDADParameter, v_ESTADOParameter, v_REGIONParameter, v_COMUNAParameter, v_DIRECCIONParameter, v_PRECIODIAParameter);
        }
    
        public virtual int SP_UPDATE_FOTODEPTO(Nullable<decimal> v_IDDEPTO, byte[] v_FOTO)
        {
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_FOTOParameter = v_FOTO != null ?
                new ObjectParameter("V_FOTO", v_FOTO) :
                new ObjectParameter("V_FOTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_FOTODEPTO", v_IDDEPTOParameter, v_FOTOParameter);
        }
    
        public virtual int SP_UPDATE_ITEMSDEPTO(Nullable<decimal> v_IDITEM, Nullable<decimal> v_IDDEPTO, string v_DESC, Nullable<decimal> v_VALOR)
        {
            var v_IDITEMParameter = v_IDITEM.HasValue ?
                new ObjectParameter("V_IDITEM", v_IDITEM) :
                new ObjectParameter("V_IDITEM", typeof(decimal));
    
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_DESCParameter = v_DESC != null ?
                new ObjectParameter("V_DESC", v_DESC) :
                new ObjectParameter("V_DESC", typeof(string));
    
            var v_VALORParameter = v_VALOR.HasValue ?
                new ObjectParameter("V_VALOR", v_VALOR) :
                new ObjectParameter("V_VALOR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_ITEMSDEPTO", v_IDITEMParameter, v_IDDEPTOParameter, v_DESCParameter, v_VALORParameter);
        }
    
        public virtual int SP_UPDATE_MULTAS(Nullable<decimal> v_IDMULTA, string v_DETALLE, Nullable<decimal> v_VALORMULTA)
        {
            var v_IDMULTAParameter = v_IDMULTA.HasValue ?
                new ObjectParameter("V_IDMULTA", v_IDMULTA) :
                new ObjectParameter("V_IDMULTA", typeof(decimal));
    
            var v_DETALLEParameter = v_DETALLE != null ?
                new ObjectParameter("V_DETALLE", v_DETALLE) :
                new ObjectParameter("V_DETALLE", typeof(string));
    
            var v_VALORMULTAParameter = v_VALORMULTA.HasValue ?
                new ObjectParameter("V_VALORMULTA", v_VALORMULTA) :
                new ObjectParameter("V_VALORMULTA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_MULTAS", v_IDMULTAParameter, v_DETALLEParameter, v_VALORMULTAParameter);
        }
    
        public virtual int SP_UPDATE_PAGORESERVA(Nullable<decimal> v_IDPAGO, Nullable<decimal> v_IDRESERVA, Nullable<System.DateTime> v_FECHAPAGO, Nullable<decimal> v_MONTO)
        {
            var v_IDPAGOParameter = v_IDPAGO.HasValue ?
                new ObjectParameter("V_IDPAGO", v_IDPAGO) :
                new ObjectParameter("V_IDPAGO", typeof(decimal));
    
            var v_IDRESERVAParameter = v_IDRESERVA.HasValue ?
                new ObjectParameter("V_IDRESERVA", v_IDRESERVA) :
                new ObjectParameter("V_IDRESERVA", typeof(decimal));
    
            var v_FECHAPAGOParameter = v_FECHAPAGO.HasValue ?
                new ObjectParameter("V_FECHAPAGO", v_FECHAPAGO) :
                new ObjectParameter("V_FECHAPAGO", typeof(System.DateTime));
    
            var v_MONTOParameter = v_MONTO.HasValue ?
                new ObjectParameter("V_MONTO", v_MONTO) :
                new ObjectParameter("V_MONTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_PAGORESERVA", v_IDPAGOParameter, v_IDRESERVAParameter, v_FECHAPAGOParameter, v_MONTOParameter);
        }
    
        public virtual int SP_UPDATE_RESERVA(Nullable<decimal> v_IDRESERVA, Nullable<decimal> v_IDUSER, Nullable<decimal> v_IDDEPTO, Nullable<System.DateTime> v_FECHARESERVA, Nullable<System.DateTime> v_FECHAINICIO, Nullable<System.DateTime> v_FECHATERMINO)
        {
            var v_IDRESERVAParameter = v_IDRESERVA.HasValue ?
                new ObjectParameter("V_IDRESERVA", v_IDRESERVA) :
                new ObjectParameter("V_IDRESERVA", typeof(decimal));
    
            var v_IDUSERParameter = v_IDUSER.HasValue ?
                new ObjectParameter("V_IDUSER", v_IDUSER) :
                new ObjectParameter("V_IDUSER", typeof(decimal));
    
            var v_IDDEPTOParameter = v_IDDEPTO.HasValue ?
                new ObjectParameter("V_IDDEPTO", v_IDDEPTO) :
                new ObjectParameter("V_IDDEPTO", typeof(decimal));
    
            var v_FECHARESERVAParameter = v_FECHARESERVA.HasValue ?
                new ObjectParameter("V_FECHARESERVA", v_FECHARESERVA) :
                new ObjectParameter("V_FECHARESERVA", typeof(System.DateTime));
    
            var v_FECHAINICIOParameter = v_FECHAINICIO.HasValue ?
                new ObjectParameter("V_FECHAINICIO", v_FECHAINICIO) :
                new ObjectParameter("V_FECHAINICIO", typeof(System.DateTime));
    
            var v_FECHATERMINOParameter = v_FECHATERMINO.HasValue ?
                new ObjectParameter("V_FECHATERMINO", v_FECHATERMINO) :
                new ObjectParameter("V_FECHATERMINO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_RESERVA", v_IDRESERVAParameter, v_IDUSERParameter, v_IDDEPTOParameter, v_FECHARESERVAParameter, v_FECHAINICIOParameter, v_FECHATERMINOParameter);
        }
    
        public virtual int SP_UPDATE_SERVICIOSEXTRA(Nullable<decimal> v_IDSERVICIO, Nullable<decimal> v_IDRESERVA, string v_NOMBRE, string v_DESC)
        {
            var v_IDSERVICIOParameter = v_IDSERVICIO.HasValue ?
                new ObjectParameter("V_IDSERVICIO", v_IDSERVICIO) :
                new ObjectParameter("V_IDSERVICIO", typeof(decimal));
    
            var v_IDRESERVAParameter = v_IDRESERVA.HasValue ?
                new ObjectParameter("V_IDRESERVA", v_IDRESERVA) :
                new ObjectParameter("V_IDRESERVA", typeof(decimal));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_DESCParameter = v_DESC != null ?
                new ObjectParameter("V_DESC", v_DESC) :
                new ObjectParameter("V_DESC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_SERVICIOSEXTRA", v_IDSERVICIOParameter, v_IDRESERVAParameter, v_NOMBREParameter, v_DESCParameter);
        }
    
        public virtual int SP_UPDATE_TIPOUSUARIO(Nullable<decimal> v_IDUSER, string v_TIPOCTA)
        {
            var v_IDUSERParameter = v_IDUSER.HasValue ?
                new ObjectParameter("V_IDUSER", v_IDUSER) :
                new ObjectParameter("V_IDUSER", typeof(decimal));
    
            var v_TIPOCTAParameter = v_TIPOCTA != null ?
                new ObjectParameter("V_TIPOCTA", v_TIPOCTA) :
                new ObjectParameter("V_TIPOCTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_TIPOUSUARIO", v_IDUSERParameter, v_TIPOCTAParameter);
        }
    
        public virtual int SP_UPDATE_USUARIOS(Nullable<decimal> v_IDUSER, string v_EMAIL, string v_TIPOCTA, string v_PNOM, string v_SNOM, string v_PAPE, string v_SAPE, Nullable<decimal> v_RUT, string v_DVER, string v_CARGO)
        {
            var v_IDUSERParameter = v_IDUSER.HasValue ?
                new ObjectParameter("V_IDUSER", v_IDUSER) :
                new ObjectParameter("V_IDUSER", typeof(decimal));
    
            var v_EMAILParameter = v_EMAIL != null ?
                new ObjectParameter("V_EMAIL", v_EMAIL) :
                new ObjectParameter("V_EMAIL", typeof(string));
    
            var v_TIPOCTAParameter = v_TIPOCTA != null ?
                new ObjectParameter("V_TIPOCTA", v_TIPOCTA) :
                new ObjectParameter("V_TIPOCTA", typeof(string));
    
            var v_PNOMParameter = v_PNOM != null ?
                new ObjectParameter("V_PNOM", v_PNOM) :
                new ObjectParameter("V_PNOM", typeof(string));
    
            var v_SNOMParameter = v_SNOM != null ?
                new ObjectParameter("V_SNOM", v_SNOM) :
                new ObjectParameter("V_SNOM", typeof(string));
    
            var v_PAPEParameter = v_PAPE != null ?
                new ObjectParameter("V_PAPE", v_PAPE) :
                new ObjectParameter("V_PAPE", typeof(string));
    
            var v_SAPEParameter = v_SAPE != null ?
                new ObjectParameter("V_SAPE", v_SAPE) :
                new ObjectParameter("V_SAPE", typeof(string));
    
            var v_RUTParameter = v_RUT.HasValue ?
                new ObjectParameter("V_RUT", v_RUT) :
                new ObjectParameter("V_RUT", typeof(decimal));
    
            var v_DVERParameter = v_DVER != null ?
                new ObjectParameter("V_DVER", v_DVER) :
                new ObjectParameter("V_DVER", typeof(string));
    
            var v_CARGOParameter = v_CARGO != null ?
                new ObjectParameter("V_CARGO", v_CARGO) :
                new ObjectParameter("V_CARGO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_USUARIOS", v_IDUSERParameter, v_EMAILParameter, v_TIPOCTAParameter, v_PNOMParameter, v_SNOMParameter, v_PAPEParameter, v_SAPEParameter, v_RUTParameter, v_DVERParameter, v_CARGOParameter);
        }
    }
}
