//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.RESERVA = new HashSet<RESERVA>();
            this.TIPO_USUARIO = new HashSet<TIPO_USUARIO>();
        }
    
        public long ID_USER { get; set; }
        public string EMAIL_USER { get; set; }
        public string TIPO_CTA { get; set; }
        public string P_NOM { get; set; }
        public string S_NOM { get; set; }
        public string P_APE { get; set; }
        public string S_APE { get; set; }
        public long RUT { get; set; }
        public string D_VER { get; set; }
        public string CARGO { get; set; }
    
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual ICollection<TIPO_USUARIO> TIPO_USUARIO { get; set; }
    }
}
